### ISSUE TITLE
string_view comparison wrong results

### ISSUE THREAD

**Issue by arteniioleg** [glynos/uri#24]
```cpp
auto u1 = network::uri{"http://localhost"};
auto u2 = network::uri{"http://localhosting"};

std::cout << (u1.host() != u2.host()) << std::endl;
std::cout << (u1.host().to_string() != u2.host().to_string()) << std::endl;

std::string_view s1 {"localhost"};
std::string_view s2 {"localhosting"};

std::cout << (s1 != s2) << std::endl;
```

**Output**

```
0 // WHAT?
1
1
```

**Comment by glynos** [comment]
Yes, I see that it's a very silly bug. I have fixed locally, I'll have the chance to integrate it over the weekend.

The string_view and optional classes implemented in this library should eventually be replaced by those implementations of the C++17 library. I have already started doing this on another branch.

Thanks for the report.

**Comment by glynos** [comment]
This has been fixed since https://github.com/glynos/uri/commit/32adc97dfbcfda1e9346079c1987a99b9a8ddd7b
